### ISSUE TITLE
error while running 

### ISSUE THREAD

**Issue by ALIrezanouri** [karthikbadam/TimeFork#3]
hi there , great job , i have tested the library before , but now while running  "node app.js " command i got this error  :

Express server listening on port 3000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND ichart.finance.yahoo.com ichart.finance.yahoo.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

what should i do ?

**Comment by FLYBYME** [comment]
Find a new http://ichart.finance.yahoo.com

The site is down..
